### ISSUE TITLE
Doesn't work on macOS

### ISSUE THREAD

**Issue by ioncodes** [tathanhdinh/keystone-rs#2]
Okay, so I tested this out on my Mac. It builds fine, but as soon as I run my tests it says
```
 = note: Undefined symbols for architecture x86_64:                            
            "_ks_close", referenced from:                                       
                _$LT$keystone..Keystone$u20$as$u20$core..ops..drop..Drop$GT$::drop::h090a6cc91f181b79 in libkeystone-5e58b880aee1b0aa.rlib(keystone-5e58b880aee1b0aa.keystone.5vko57k1-cgu.5.rcgu.o)
            "_ks_option", referenced from:                                      
                keystone::Keystone::option::h5ce75ad5f471b4ab in libkeystone-5e58b880aee1b0aa.rlib(keystone-5e58b880aee1b0aa.keystone.5vko57k1-cgu.5.rcgu.o)
            "_ks_asm", referenced from:                                         
                keystone::Keystone::asm::hc1d0628a379e9f76 in libkeystone-5e58b880aee1b0aa.rlib(keystone-5e58b880aee1b0aa.keystone.5vko57k1-cgu.5.rcgu.o)
            "_ks_version", referenced from:                                     
                keystone::version::h1ce073e872c5a89e in libkeystone-5e58b880aee1b0aa.rlib(keystone-5e58b880aee1b0aa.keystone.5vko57k1-cgu.5.rcgu.o)
            "_ks_errno", referenced from:                                       
                keystone::Keystone::asm::hc1d0628a379e9f76 in libkeystone-5e58b880aee1b0aa.rlib(keystone-5e58b880aee1b0aa.keystone.5vko57k1-cgu.5.rcgu.o)
            "_ks_free", referenced from:                                        
                keystone::Keystone::asm::hc1d0628a379e9f76 in libkeystone-5e58b880aee1b0aa.rlib(keystone-5e58b880aee1b0aa.keystone.5vko57k1-cgu.5.rcgu.o)
            "_ks_open", referenced from:                                        
                keystone::Keystone::new::h6c2d95bfd302784e in libkeystone-5e58b880aee1b0aa.rlib(keystone-5e58b880aee1b0aa.keystone.5vko57k1-cgu.5.rcgu.o)
          ld: symbol(s) not found for architecture x86_64                       
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This happens when I run `cargo test` on this [project](https://github.com/ioncodes/sam/tree/native) (the "native" branch).

However, `cargo build` reports no issues. Any ideas?

**Comment by tathanhdinh** [comment]
@ioncodes many thanks for the report, could you please check the latest commit to see if this works?
I've fixed some bugs but I've no Mac to check.

**Comment by ioncodes** [comment]
Unfortunately a new error pops up. The message I get after running ```cargo test``` and/or ```cargo build``` is:
```
Compiling keystone-sys v0.1.0 (https://github.com/tathanhdinh/keystone-rs?branch=new_build_system#2276035b)  
error: could not find native static library `keystone`, perhaps an -L flag is missing?
```

I hope this helps!

PS: I'm wondering which command is expecting a flag called `L`. `cargo test` and `cargo build` certainly do not accept a flag called `L`.

**Comment by ioncodes** [comment]
I just noticed that `keystone-sys` looks for a library called `keystone`. However, I'm not sure if *nix platforms resolve the name automatically, but the library is called `libkeystone`!

**Comment by ioncodes** [comment]
Is it possible that you have `keystone`/`libkeystone` installed globally already? In that case your test would have successfully built. I don't see any installation code in your buildscript, nor do I see any direct access to the library during the compilation steps (gcc's `L` flag?). I don't have keystone installed globally afaik, however, these are just thoughts, I don't know much about custom build systems of Rust.

**Comment by mteyssier** [comment]
Hi @ioncodes, I might have got the same error about finding library `keystone` on debian.

The library search path is set in `keystone-sys/build.rs` by `"cargo:rustc-link-search={}={}/lib64"` (and ends up as a `-L` flag passed to `rustc`, you can see it using `cargo build -v`)
However on debian (and macOS?) the library is built to `{}/lib`

I have no Mac to check, but the PR #3 might fix it for macOS too.

**Comment by tathanhdinh** [comment]
@mteyssier many thanks for the help, I don't even know the meaning of `CMAKE_INSTALL_LIBDIR` :(
@ioncodes could you please check if the PR works on Mac?

**Comment by ioncodes** [comment]
Sorry for the late response! I will do that in a few minutes!

**Comment by mteyssier** [comment]
I couldn't help but leverage travis-ci to test some builds on macos https://travis-ci.org/mteyssier/keystone-rs/jobs/442822741
The PR #3 helps and `cargo build` runs fine.
However there is still some link issue when building the tests. Most likely because macos is using `libc++` instead of `libstdc++`.
A simple fix would be to link with `libc++` on macos: mteyssier/keystone-rs@697f7ee6056bee650742eb4bbf0db1c219a92ef1

@ioncodes you would probably get the same issue, you might want to try the [fix_macos_build branch in mteyssier/keystone-rs](https://github.com/mteyssier/keystone-rs/tree/fix_macos_build).
It builds on macos in travis-ci https://travis-ci.org/mteyssier/keystone-rs/builds/442902781

@tathanhdinh if the fix is ok, would you like a new PR? Should I update #3? Close #3 and make a new PR with both fixes?

> @mteyssier many thanks for the help, I don't even know the meaning of `CMAKE_INSTALL_LIBDIR` :(

No problem. I didn't know this specific option either. I ended up on https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html after browsing some [keystone-engine/keystone](https://github.com/keystone-engine/keystone)

**Comment by ioncodes** [comment]
@mteyssier Sorry for letting you wait! I tested it out and it does indeed build on my machine now! @tathanhdinh Would be awesome if you could merge those changes!

![test](https://i.imgur.com/k1GlBDu.png)

**Comment by tathanhdinh** [comment]
@ioncodes thanks for the feedback.
@mteyssier thanks again for the fix, this is awesome. Could you please just update #3 ?

**Comment by mteyssier** [comment]
@ioncodes Nice! Glad I could help. Thanks for testing and previous reports.
@tathanhdinh Np. #3 is now updated.

**Comment by tathanhdinh** [comment]
Thanks for the awesome work, #3 merged.
